In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd

matrix_3x2 = np.array([[1, 1], [2, 2], [3, 3]])
matrix_2x3 = np.array([[1, 1, 1], [2, 2, 3]])

print('3 x 2 matrix : \n', matrix_3x2)
print('\n 2 x 3 matrix : \n', matrix_2x3)

3 x 2 matrix : 
 [[1 1]
 [2 2]
 [3 3]]

 2 x 3 matrix : 
 [[1 1 1]
 [2 2 3]]


In [ ]:
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.12913021 0.39774488 0.14461894 0.72723548]
 [0.3765452  0.72208527 0.01993635 0.44659192]
 [0.36201232 0.84676007 0.40310586 0.56729522]]


In [ ]:
# matrix multiplication
matrix_mul = np.dot(matrix_3x2, matrix_2x3)
print(matrix_mul)

[[ 3  3  4]
 [ 6  6  8]
 [ 9  9 12]]


In [ ]:
# elemet wise matrix multiplication
ans= [[0 for x in range(len(matrix_3x2))] for y in range(len(matrix_2x3[0]))]

for i in range(len(matrix_3x2)): 
  for j in range(len(matrix_2x3[0])): 
    for k in range(len(matrix_2x3)): 
      ans[i][j] += matrix_3x2[i][k] * matrix_2x3[k][j]
 
print('Element wise multiplication : \n', ans)

Element wise multiplication : 
 [[3, 3, 4], [6, 6, 8], [9, 9, 12]]


In [ ]:
mean_1 = np.mean(matrix_3x2)
mean_2 = np.mean(matrix_2x3)
print(mean_1)
print(mean_2)

2.0
1.6666666666666667


In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/LAB 1/mtcars.csv')

In [ ]:
del data['model']

meancenter = data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
