In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [ ]:
# Imports
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [ ]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [ ]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:

# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 69.,  96.,  70.],
         [ 69.,  96.,  70.],
         [102.,  43.,  37.],
         [102.,  43.,  37.],
         [ 87., 134.,  58.]]), tensor([[103., 119.],
         [103., 119.],
         [ 22.,  37.],
         [ 22.,  37.],
         [119., 133.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [ ]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[ 0.0325,  0.2916,  0.4884],
        [ 0.2925, -0.3244,  0.1797]], requires_grad=True)
---------
Parameter containing:
tensor([-0.5062,  0.4737], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [ ]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [ ]:
# Import nn.functional
import torch.nn.functional as F

In [ ]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(5038.0791, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [ ]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))


In [ ]:

# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(18.3357, grad_fn=<MseLossBackward>)


In [ ]:

# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 57.8644,  71.9164],
        [ 82.3874,  99.5287],
        [116.7412, 132.1721],
        [ 25.9406,  46.3079],
        [ 99.3286, 111.8805],
        [ 57.8644,  71.9164],
        [ 82.3874,  99.5287],
        [116.7412, 132.1721],
        [ 25.9406,  46.3079],
        [ 99.3286, 111.8805],
        [ 57.8644,  71.9164],
        [ 82.3874,  99.5287],
        [116.7412, 132.1721],
        [ 25.9406,  46.3079],
        [ 99.3286, 111.8805]], grad_fn=<AddmmBackward>)

In [ ]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [ ]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(3.2173, grad_fn=<MseLossBackward>)


## Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
 
 
## Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [ ]:

# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.19738146 0.39705544 0.06438604]
 [0.1540972  0.81889796 0.2578472 ]]
Biases:
[[0.42894587 0.25137366]
 [0.92584053 0.17489977]
 [0.4144689  0.03651504]
 [0.57417822 0.08527929]
 [0.10792543 0.24702541]
 [0.47482588 0.09944891]
 [0.17402426 0.29347468]
 [0.95320747 0.35418519]
 [0.53101817 0.69208015]
 [0.48964527 0.38948059]
 [0.9567302  0.87854485]
 [0.18504278 0.01516808]
 [0.30282235 0.7849417 ]
 [0.05447245 0.97725767]
 [0.74827608 0.08065602]]


In [ ]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [ ]:

# Generate predictions
preds = model(inputs)

In [ ]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[ 44.20910669  77.45406233]
 [ 57.94913872 102.76298641]
 [ 74.52647507 138.13043571]
 [ 40.16275475  60.55615269]
 [ 56.35159117 107.54324042]
 [ 44.25498671  77.30213757]
 [ 57.19732245 102.88156132]
 [ 75.06521365 138.44810586]
 [ 40.1195947   61.16295356]
 [ 56.73331101 107.6856956 ]
 [ 44.73689102  78.08123351]
 [ 57.20834097 102.60325472]
 [ 74.41482853 138.87886237]
 [ 39.64304898  61.44813107]
 [ 56.99194183 107.37687103]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [ ]:
# Compute loss
loss = mse(preds, targets)
print(loss)

1184.765074752429


In [ ]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[-3283.3041686  -4984.9691982  -2861.42046794]
 [ 1141.91142653   533.14072872   337.9990263 ]]
biases_grad:
[[-1.57211911  0.99387498]
 [-3.07344817  0.23506485]
 [-5.92980332  0.6840581 ]
 [ 2.42170063  3.14082036]
 [-6.21978784 -1.52756794]
 [-1.56600177  0.97361834]
 [-3.17369034  0.25087484]
 [-5.85797151  0.72641411]
 [ 2.41594596  3.22172714]
 [-6.16889187 -1.50857392]
 [-1.50174786  1.0774978 ]
 [-3.1722212   0.2137673 ]
 [-5.94468953  0.78384832]
 [ 2.35240653  3.25975081]
 [-6.13440776 -1.54975053]]


Adjust weights

In [ ]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [ ]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.2302145  0.44690513 0.09300025]
 [0.14267809 0.81356655 0.25446721]]
Biases:
[[0.42896159 0.25136373]
 [0.92587126 0.17489742]
 [0.41452819 0.0365082 ]
 [0.57415401 0.08524788]
 [0.10798763 0.24704069]
 [0.47484154 0.09943917]
 [0.17405599 0.29347217]
 [0.95326605 0.35417792]
 [0.53099401 0.69204794]
 [0.48970695 0.38949567]
 [0.95674522 0.87853407]
 [0.1850745  0.01516594]
 [0.3028818  0.78493386]
 [0.05444893 0.97722507]
 [0.74833743 0.08067152]]


In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

808.877920773181


In [ ]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

39.006671253005884


In [ ]:
# Print predictions
print(preds)

[[ 57.97723377  70.86650524]
 [ 80.48700904  97.36634809]
 [122.11861633 138.73059063]
 [ 25.48863455  39.84591898]
 [ 95.36301363 111.85263374]
 [ 58.02310149  70.7146212 ]
 [ 79.73539422  97.48489123]
 [122.65721055 139.04817565]
 [ 25.44548606  40.45255724]
 [ 95.74463118 111.99505074]
 [ 58.50487667  71.49350836]
 [ 79.74640979  97.2066592 ]
 [122.00699971 139.47881674]
 [ 24.96906805  40.73765834]
 [ 96.00319269 111.68630892]]


In [ ]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
